site_name: Pimple Config Service Provider
site_description: Pimple Config Service Provider based on Illuminate Config package for Silex Microframework or any Pimple Container project's.
site_author: http://nunopress.com

repo_name: Github
repo_url: https://github.com/nunopress/pimple-config-service-provider

copyright: Copyright (c) 2010-2016 NunoPress LLC - License MIT

markdown_extensions:
  - admonition