site_name: Pimple Config Service Provider
site_description: Pimple Config Service Provider based on Illuminate Config package for Silex Microframework or any Pimple Container project's.
site_author: http://nunopress.com

theme: readthedocs
docs_dir: docs

repo_url: https://github.com/nunopress/pimple-config-service-provider/

copyright: Copyright &copy; 2010-2016 <a href="http://nunopress.com">NunoPress LLC</a> - License MIT

markdown_extensions:
  - admonition:
