# ----
# Site

title: Config Service Provider
description: Config Service Provider based on Illuminate Config package for Silex Microframework or any Pimple Container project's.
url: https://github.com/nunopress/config-service-provider
google_analytics_key:

collections:
  documentation:
    title: Documentation
    position: 1
  api:
    title: APIs
    position: 2
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE
  
defaults:
  -
    scope:
      path: "config-service-provider/"
    values:
      layout: default

# -----
# Build


# -----------
# CloudCannon

version: 3.0.3
